### PR TITLE
DOMready + Clean JSONP + Manual init

### PR DESCRIPTION
**Pull request by bloodyowl**
- Removes JSONPCallback after it's executed to prevent unwanted access
- Removed script element once loaded (with JSONP)
- Added fragment.evaluate method
- Removed automatic parsing
- Stronger xhr.status check

### CODE REVIEW

**Comment by bloodyowl** [comment]
Changes can be seen here : http://mlbli.github.com/fragment.js/

**Comment by DanielRapp** [comment]
Looks great! A few questions though:
1. What does the `;` do on [the first line](https://github.com/mlbli/fragment.js/blob/master/fragment.js#L1)?
2. Please follow the whitespace conventions of the rest of the script by using `if (` instead of `if(` :)
3. Is there any reason `parent` isn't declared in the more restrictive `JSONPCallback` scope at [line 45](https://github.com/mlbli/fragment.js/blob/master/fragment.js#L45)?
4. Not sure how I feel about the timeout loop at [line 87](https://github.com/mlbli/fragment.js/blob/master/fragment.js#L87). Couldn't we just check in the `JSONPCallback` and/or `xhr.onreadystatechange`?
5. I realize it's kind of taboo to run libraries automatically onload, but I really liked the user not even needing to understand JS to use fragment.js. Any particular reason, other than convention, that you removed automatic evaluation?

**Comment by bloodyowl** [comment]
1. The first semicolon is a good way to make sure that the script will be well parsed (a new line followed by a `(` is interpreted as a function call if there is no semicolon in the script before, in case you concatenate files)
2. Sorry about that, didn't notice, I'll change that. 
3. In some IE versions, this can be buggy, it's just a safety.
4. The timeout loop is part of the DOM ready checker, it's one of the most lightweight solutions you can find to prevent your script from not being executed when the `document.readyState` isn't complete, and the one at [line 78](https://github.com/mlbli/fragment.js/blob/master/fragment.js#L78) makes sure that if an error occurs in the `evaluate` function, it will not break further (as an event callback). 
5. The main reason I thought this was a better idea is that you may want to limit the scope in the first place, as `querySelectorAll` calls with only attributes as parameters are quite expensive.

**Comment by DanielRapp** [comment]
3.Which versions? If you hadn't noticed, this script doesn't support IE < 8 (`querySelectorAll`), or even IE == 8 (`forEach`), so that might not be an issue. :)
5.Sounds reasonable. But if you don't mind, I'm going to make it opt-out, instead of opt-in. Meaning, a `fragment.manual` for users who want finer-grained control.

**Pull request merged**
