### PR TITLE
Add CommonJS and AMD support

### PR DESCRIPTION
**Pull request by anthonyshort**
This will let us use fragment with things like Browserify and Component :)

### CODE REVIEW

**Comment by DanielRapp** [comment]
Thanks! I've been meaning to add this :)

**Comment by DanielRapp** [comment]
What the heck happened? I'm not seeing the changes. Did I just close it without pulling the request? I'm not seeing the changes in your branch either...

**Comment by anthonyshort** [comment]
I think maybe you closed it, and I deleted the branch. I've restored the branch. Maybe you can reopen and merge it now?

**Comment by DanielRapp** [comment]
There we go, thanks :)

**Pull request merged**
