### PR TITLE
Nested templates in fragment.js

### PR DESCRIPTION
**Pull request by foopq**
Hello, I've made a few small changes to fragment.js that allows it to have nested templates and cascading interpolation contexts.

I added a small tweak to handle engines like Chrome that sometimes call xhr.onreadystatechange multiple times when readyState is 4. I also added a simple trim() around the one check for an empty innerHTML (necessary if body is the template context).

By all means, please grab these changes if they seem useful to you, thanks.

### CODE REVIEW

**Comment by DanielRapp** [comment]
Looks great!
Just writing this here so I don't forget it:
- Remove fragment.trim, use String.prototype.trim (fragment doesn't work on ie < 9 anyway)
- Make [scope/recursion code](https://github.com/DanielRapp/fragment.js/pull/14/files#L0R114) DRY (maybe move into render?)

**Comment by DanielRapp** [comment]
Actually, I'm reverting this. It doesn't work the /examples/index.html example

**Comment by foopq** [comment]
Very strange.. and my bad for not testing with the included examples (I had my own tests for this). I'll fix it.

**Comment by foopq** [comment]
I took a look and I'm wondering if there might be something else going on.. If I roll back to before my code and try the example out, it doesn't seem to work. It looks like the media check on "(max-width: 500px)" is failing. If I set it to min-width instead, it works. I haven't played with matchMedia before, so perhaps I'm overlooking something.. but it seems like there's an issue independent of my code..

**Comment by DanielRapp** [comment]
You're right, your code is working correctly. I forgot to reset changes completely before reverting. I'll try to re-merge :)

**Comment by foopq** [comment]
Cool.. do you need me to another pull request?

**Comment by DanielRapp** [comment]
Pardon my tardiness, I haven't gotten around to merging yet as I've been busy. If you created another pull request, that'd really help. Thanks :)

**Pull request merged**
